### ISSUE TITLE
plugin not loading on personal getsentry

### ISSUE THREAD

**Issue by jeroenbourgois** [getsentry/sentry-slack#10]
Hi

sorry for the dummy question, but I installed the package with pip on my sentry server, but the plugin doesn't show up. I cannot find a lot of documentation, do I need to add `sentry-slack` to a config file to load it? I tried restarting `supervisor` but that does not do the trick...

**Comment by carlitux** [comment]
I have installed sentry 8.13.0 and I have the plugins listed in Admin -> Packages like sentry_plugins.gitlab.plugin.GitLabPlugin

But when I go into a **All Integrations** in project settings page it is empty.

**Comment by dcramer** [comment]
@carlitux this isnt a place for support. Please see our support options:

https://sentry.io/support/

That said, you're certainly misunderstanding things or dont have them configured correctly, as the plugins work fine.
