### ISSUE TITLE
Save button doesn't work with sentry 7.1.2

### ISSUE THREAD

**Issue by zelo** [getsentry/sentry-slack#12]
When I try to add slack webhook and i paste it in to input box and i save. It won't be saved even if the notification says otherwise. To actually save the webhook i have to paste it and then press enter.

This is reason why #3 is occuring.

**Comment by neoecos** [comment]
You're right!

Looks like this is a sentry bug, not really a plugin bug.

**Comment by dcramer** [comment]
Unable to reproduce in master. Are you seeing a JS error or similar?

The form is pretty simple, and unless you're clicking the test button instead of save there's no clear way this wouldn't work to me.

Feel free to reopen if you can provide more information on how to reproduce.
