### ISSUE TITLE
Weird KeyError with string "slack" in sentry internal. Seems slack related. 

### ISSUE THREAD

**Issue by arturaz** [getsentry/sentry-slack#19]
Installed plugin to on-premise sentry as told in README.

Set it up via sentry. Restarted both sentry & celery. Test messages work. Nothing else gets reported.

http://errors.tinylabproductions.com/tlp/internal/group/11/

**Comment by dcramer** [comment]
@arturaz you may try installing sentry-slack from git, as we're pretty inconsistent about pushing out releases to some of these

**Comment by arturaz** [comment]
How do you install it from git?

**Comment by mattrobenolt** [comment]
@arturaz 

You can just do something like:

```
$ pip install -e git+https://github.com/getsentry/sentry-slack.git@1813d3e0a44246a1757138070a9864bdf3a7ae6c#egg=sentry_slack-dev
```

**Comment by dcramer** [comment]
Alternatively just do this:

```
pip install https://github.com/getsentry/sentry-slack/archive/master.zip
```

**Comment by mattrobenolt** [comment]
A new version has been tagged and uploaded to pypi. https://pypi.python.org/pypi/sentry-slack/0.3.0

plz reopen if this is still an issue with 0.3.0

**Comment by arturaz** [comment]
I've installed 0.3.0 from master, restarted sentry and now it just says: "There was an internal error with the Plugin" when I try to test it. Nothing in sentry or celery logs :/
