### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by mjdavies** [getsentry/sentry-slack#23]
Hello there

I'm being a bit dull at the moment, and I'm struggling to understand how to use the new "Include triggering rules with notifications" option in the slack setup on my sentry install.

Could you give me a use case example of what that means, and how to achieve it?

Thanks in advance.

**Comment by mjdavies** [comment]
I would label this as a question obviously, but I can't :-(

**Comment by dcramer** [comment]
@mjdavies this is our fault for not making it clear what this is. It simply adds a blurb to the Slack notification which tells you which Rules caused the notification to be generated.

**Comment by mjdavies** [comment]
Thanks David
