### ISSUE TITLE
0.4.0 broken with Sentry 7.1.x

### ISSUE THREAD

**Issue by jwmarshall** [getsentry/sentry-slack#24]
FYI, I recently rebuilt my sentry docker image and found that version 0.4.0 of this plugin does not work properly with the 7.1 branch of Sentry. You may want to update the setup.py to reflect this. Not sure which version it starts to work with exactly. To fix I downgraded to 0.2.0.

**Comment by steffenmllr** [comment]
Same issue here, downgrading helped thanks @jwmarshall

**Comment by Bruce17** [comment]
We have the same issue here too with Sentry 7.7.1.

We cannot downgrade, because of a version conflict with "kombu".

**Comment by ChristianGfK** [comment]
At least what @Bruce17 mentioned was a result of this problem: https://github.com/getsentry/sentry/pull/2233

**Comment by Rambomst** [comment]
I am also having this issue and downgrading to 0.2.0 hasn't resolved the issue.

**Comment by mattrobenolt** [comment]
@Rambomst You referring to the issue with kombu?

**Comment by Rambomst** [comment]
@mattrobenolt I am referring to @jwmarshall's issue about version 0.4.0 not working with the version 7.7.1 of Sentry.

**Comment by jwmarshall** [comment]
FWIW My problem was with sentry 7.1.x if you're having issues with 7.7.x it looks like the recommended solution is to force celery to version 3.1.18. @ChristianGfK might be able to offer specific instructions that worked for him.

**Comment by ChristianGfK** [comment]
I just grabbed the 7.7.1 release tarball, extracted it, changed `setup.py` according to https://github.com/getsentry/sentry/pull/2233/files and ran `pip install sentry-7.7.1/`.

**Comment by Rambomst** [comment]
Right, rolling back celery works. Thanks.

**Comment by karmux** [comment]
Sentry 7.7.4 and Sentry-Slack 0.4.0 don't work together too.

**Comment by mattrobenolt** [comment]
What's the issue you're having?

--
Matt Robenolt
@mattrobenolt




On Wed, Nov 18, 2015 at 7:14 AM -0800, "Karmo Rosental" <notifications@github.com> wrote:












Sentry 7.7.4 and Sentry-Slack 0.4.0 don't work together too.

**Comment by karmux** [comment]
After I updated Sentry from 7.7.0 to 7.7.4 and Sentry-Slack from 0.2.0 to 0.4.0 Slack doesn't receive any messages. Configuration test in Webhook passes.

**Comment by mattrobenolt** [comment]
Does it work fine with 0.3? You made a lot of big jumps there. :/

--
Matt Robenolt
@mattrobenolt




On Wed, Nov 18, 2015 at 7:21 AM -0800, "Karmo Rosental" <notifications@github.com> wrote:












After I updated Sentry from 7.7.0 to 7.7.4 and Sentry-Slack from 0.2.0 to 0.4.0 Slack doesn't receive any messages. Configuration test in Webhook passes.

**Comment by mattrobenolt** [comment]
Oh, sorry, I misread. From 7.7.0 to 7.7.4 has basically no changes. 
So do thinks work with 0.3.x? If so, I'll investigate. 

--
Matt Robenolt
@mattrobenolt




On Wed, Nov 18, 2015 at 7:21 AM -0800, "Karmo Rosental" <notifications@github.com> wrote:












After I updated Sentry from 7.7.0 to 7.7.4 and Sentry-Slack from 0.2.0 to 0.4.0 Slack doesn't receive any messages. Configuration test in Webhook passes.

**Comment by karmux** [comment]
I tested it with various version combinations.

Sentry 7.7.0 and sentry-slack 0.4.0 works well together.
Sentry 7.7.4 and sentry-slack 0.4.0 doesn't work (Sentry submenu is also missing from left side menu).

**Comment by mattrobenolt** [comment]
@karmux I'm not sure what's going on, but this seems unrelated. I assure you, nothing between 7.7.0 and 7.7.4 changed with regard to this.

7.7.1->7.7.4 were just pinning dependencies because an upstream package broke something.

Do you mind opening an issue on https://github.com/getsentry/sentry since this is unrelated to the Slack plugin.

I'm also closing this ticket since it's far off topic.
