### ISSUE TITLE
README should mention that the wsgi service needs to be restarted after installation

### ISSUE THREAD

**Issue by thefinn93** [getsentry/sentry-slack#25]
Maybe this is obvious, but the way the README is written it sounds like after you run `pip` it'll just show up, but in fact gunicorn or whatever needs to be restarted (or at least, it started working for me until I restarted `sentry-web`). Maybe the README should be updated?

**Comment by dcramer** [comment]
This is true of all Sentry extensions (and all libraries in a lot of languages). You have to restart the entirety of the service.

I dont think it's worth the effort updating the 100 repos that are extensions with this, but if anything we should explain it in the on-premise docs. That said, very few people would likely read them anyways so we'd end up in the same spot.
