### ISSUE TITLE
Not working on Sentry 7.7.4

### ISSUE THREAD

**Issue by artdude543** [getsentry/sentry-slack#29]
Just updated my Sentry install and the Slack plugin now fails with `There was an internal error with the Plugin`.

Not sure where to find logs but if you point me to the right location I'll grab them for you.

**Comment by milanvanschaik** [comment]
+1
I was wondering why it didn't appear.. I don't get any error message or so. Also there was nothing in the gunicorn error log.

**Comment by petecoop** [comment]
Have just upgraded to Sentry 8 and get this too :(

**Comment by petecoop** [comment]
Got it working again by commenting out the lines with `username` in `plugin.py`

**Comment by mattrobenolt** [comment]
This was fixed with 0.5.0.

**Comment by juniorrocha** [comment]
Hi, I'm using Sentry 8.4.0dev0 with Slack Plugin 0.5.5 and I had the same problem.
