### ISSUE TITLE
Rule edit URLs in notification are relative.

### ISSUE THREAD

**Issue by dreid** [getsentry/sentry-slack#30]
Slack displays these as: `</org-slug/project-slug/rule-id/edit | Rule name>` instead of a link.

**Comment by alex** [comment]
https://github.com/getsentry/sentry-slack/blob/master/src/sentry_slack/plugin.py#L157-L159 is the bug, needs the host added

**Comment by mattrobenolt** [comment]
Ah. Will fix. Thanks. :)

**Comment by mattrobenolt** [comment]
This will go out to getsentry.com today, if you're not using us, you know how to update. ;)

Thanks again!

**Comment by caske33** [comment]
@mattrobenolt Is it possible to make another release on github as well?
