### ISSUE TITLE
Installing the plugin for celery workers

### ISSUE THREAD

**Issue by andrzejwp** [getsentry/sentry-slack#32]
I'm running sentry in docker. 
I have separate containers for the main sentry image, redis, postgres, celery beat and celery workers. After installing the sentry-slack plugin (via pip) in the sentry container the integration wasn't working, I had to install it on the celery-worker containers as well. Please mention that in the README.md.

**Comment by dcramer** [comment]
You have to install things on all application instances. I'm not against documenting it, but this is also one of those "if you are operating it, you should generally have a solid understand of how the software works". This is a standard thing across all platforms and languages. While Sentry could add magic to try and transfer things to servers, it never will, nor will many other things.
