### ISSUE TITLE
Latest version does not work on Sentry v8.0.5

### ISSUE THREAD

**Issue by esn89** [getsentry/sentry-slack#34]
On my self-hosted sentry:

When my projects do fail, the Slack notification does not work on my channel.  However, when I added the webhook and pressed "Test Configuration" I get the notifications as seen here:

https://i.imgur.com/9b8kTP2.png

I've ensured that the notification settings for Slack and email for the project is enabled, and that it is set to "when an event is seen" and not "when an event is first seen"

Any ideas why as to why it works on testing the configuration but not when a project fails?

**Comment by erichelgeson** [comment]
I had the same issue, it turns out my workers didn't have the plugin installed (testing from the web used a different python env). Or maybe your workers need a restart.

**Comment by mattrobenolt** [comment]
Out of curiosity, how does this happen? Plugins being installed for web processes and workers? This seems to be a semi-common issue with plugins and workers running different config files, and I'd like to understand this a bit more how this situation even happens and what we could do to help.

**Comment by erichelgeson** [comment]
My situation was using the docker image, I was using the 8-ONBUILD one. I started the web with the custom `requirements.txt` in it, the workers accidentally without.

How I installed (fixed) -  https://gist.github.com/erichelgeson/6c2ef4b423d1ea8fac48

**Comment by mattrobenolt** [comment]
Good to know. Thanks. :)

I'm closing this ticket since there isn't much we can do here besides possibly figure out a way to message that the workers are running different plugins/config.

**Comment by Sk1Zy** [comment]
@mattrobenolt I'm having the same problem as @erichelgeson 

I have a custom image which is very similar to @erichelgeson script. I am running my sentry worker and sentry beat and the web interface using this image. It shows up in the interface and I can configure it just fine there and the test button sends a notification to slack.

But when an error occurs in any of my applications there is no notification sent to slack.

Any ideas?
