### ISSUE TITLE
notification doesn't contain link back to issue

### ISSUE THREAD

**Issue by lynchc** [getsentry/sentry-slack#35]
It used to. I upgraded everything to use sentry8 and the latest plugin and now I can't get the notification to include a link back to the issue.

Any ideas?

Thanks

**Comment by dcramer** [comment]
@lynchc is system.url-prefix configured?

**Comment by dcramer** [comment]
Closing this as I think it's a config error, but if you have more information that suggests its not please re-open.

**Comment by lynchc** [comment]
I have SENTRY_URL_PREFIX configured in the config file. is there some place else that it needs to be configured?

**Comment by dcramer** [comment]
@lynchc do you see an odd relative URL (i.e. </foo/bar/issues/1234134>)

**Comment by lynchc** [comment]
i the slack payload, I don't see any link at all

**Comment by dcramer** [comment]
@lynchc can you share a screenshot or copy paste the text (redacting anything sensitive)

**Comment by lynchc** [comment]
![screen shot 2016-02-01 at 2 21 48 pm](https://cloud.githubusercontent.com/assets/3439990/12733428/ad4b2f1a-c8ef-11e5-87c3-623474bb636e.png)

**Comment by dcramer** [comment]
@lynchc we're looking into this, but a quick fix might be to go to your Sentry dashboard, click your avatar and go to "Admin", from there click "Settings". Make sure Root URL is filled out there.

**Comment by mattrobenolt** [comment]
Hey @lynchc, are you sure you have `sentry-slack` 0.5.0 installed? This was an issue before, but it was fixed. See: #30 

Make sure 0.5.0 exists on both the web processes and worker processes.

**Comment by lynchc** [comment]
root url was filled out with the same info that was in the config file.

I have version 0.4.0 installed. I'll upgrade now and see if it goes away

**Comment by lynchc** [comment]
upgraded to sentry 8.0.6 and sentry-slack 0.5.0

Now I see this error when testing slack config:
[ERROR] Plugin(slack) raised an error during test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/base/configuration.py", line 41, in default_plugin_config
    test_results = plugin.test_configuration(project)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 156, in test_configuration
    return self.notify(notification)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_slack/plugin.py", line 196, in notify
    std_key = TagKey.get_standardized_key(key)
AttributeError: type object 'TagKey' has no attribute 'get_standardized_key'

**Comment by lynchc** [comment]
removing tags from the notif fixes that and test config works. notifs come in automatically again but still without any links

**Comment by dcramer** [comment]
Looks like sentry-slack is going to require Sentry 8.1, sorry about that.

Its getting pushed out shortly.

**Comment by mattrobenolt** [comment]
8.1 was released today, so closing this issue.
