### ISSUE TITLE
sentry-slack sentry 8.2.2

### ISSUE THREAD

**Issue by Hrafnkellos** [getsentry/sentry-slack#39]
Hi im trying to install sentry slack for sentry 8.2.2 but i cant see that sentry slack pops up in the Integrations list.

**Comment by dblenkus** [comment]
I have the same issue with sentry 8.2.3

**Comment by mattrobenolt** [comment]
Can you you provide any more information? When Sentry starts up, it should dump out an error while loading the plugin if that's the case. It'd be like:

```
Failed to load plugin: 'slack'
```

With a stacktrace.

**Comment by dblenkus** [comment]
There is no mention of `slack` when `sentry` starts:

``root@web01:/srv/sentry# /srv/sentry/venv/bin/sentry --config=/srv/sentry/sentry.conf.py start
Running service: 'http'
*** Starting uWSGI 2.0.12 (64bit) on [Wed Mar 16 16:36:43 2016] ***
compiled with version: 4.7.2 on 16 March 2016 09:32:25
os: Linux-3.4.4 #1 SMP Wed Jul 18 01:32:13 CEST 2012
nodename: web01
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/sentry
detected binary path: /srv/sentry/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your processes number limit is 23416
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 4
Python version: 2.7.3 (default, Mar 13 2014, 11:26:58)  [GCC 4.7.2]
Set PythonHome to /srv/sentry/venv
Python main interpreter initialized at 0xe2ee60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1441536 bytes (1407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 10166)
spawned uWSGI worker 1 (pid: 10173, cores: 4)
spawned uWSGI worker 2 (pid: 10174, cores: 4)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xe2ee60 pid: 10173 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xe2ee60 pid: 10174 (default app)``

**Comment by mattrobenolt** [comment]
What if you do:

```
$ sentry plugins list
```

**Comment by dblenkus** [comment]
There is no output:
```
(venv)root@web01:/srv/sentry# /srv/sentry/venv/bin/sentry --config=/srv/sentry/sentry.conf.py plugins list
(venv)root@web01:/srv/sentry#
```

**Comment by mattrobenolt** [comment]
Then it's not installed. :)

**Comment by dblenkus** [comment]
`pip freeze` lists `sentry-slack==0.5.0` so the package is installed. I've followed instructions and ran `pip install sentry-slack`. Is there anything more to do? Maybe add it to the `INSTALLED_APPS`?

**Comment by mattrobenolt** [comment]
Are you running `pip` from within the same virtualenv? In your case, it'd be `/srv/sentry/venv/bin/pip`

**Comment by dblenkus** [comment]
Yes, I've double checked and `/srv/sentry/venv/bin/pip freeze` returns the same list.

**Comment by mitsuhiko** [comment]
Hey @dblenkus, can you run this and print the output?

```
>>> from pkg_resources import iter_entry_points
>>> list(iter_entry_points('sentry.plugins'))
[...]
```

**Comment by dblenkus** [comment]
```
root@web01:~# source /srv/sentry/venv/bin/activate
(venv)root@web01:~# python
Python 2.7.3 (default, Jan  2 2013, 13:56:14)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import iter_entry_points
>>> list(iter_entry_points('sentry.plugins'))
[]
```

**Comment by mitsuhiko** [comment]
It sounds like your virtualenv or setuptools is broken. Try to reinitialize the venv, update setuptools etc. This is not an issue with sentry or the plugin.

**Comment by dblenkus** [comment]
Thanks for pointing this out! It works perfect after updating pip and recreating virtualenv.
