### ISSUE TITLE
Slack integration doesn't show up

### ISSUE THREAD

**Issue by greenik** [getsentry/sentry-slack#40]
sentry: 8.2.2

There's no Slack integration in Team -> Settings -> All integrations.
In admin section in packages it's showing up correctly.

**Comment by mattrobenolt** [comment]
Does it show when you do `sentry plugins list`?

**Comment by greenik** [comment]
Yes, it is showing there.

**Comment by mattrobenolt** [comment]
Then everythign is fine, I'm guessing you haven't restarted your web processes. There's no other reason it wouldn't be shown.

**Comment by greenik** [comment]
I've restarted them few times while configurating things, but still nothing on version 8.2.2.
But today I've updated sentry to newest version(8.3.1) and it's showing up normally.
