### ISSUE TITLE
Errors are not being sent to Slack

### ISSUE THREAD

**Issue by orlando** [getsentry/sentry-slack#45]
Hello guys,

I got the Slack integration setup in a Docker container. Test configuration works and posts to a Slack channel, but when I sent errors using the `raven-go` and the `raven-js` clients, these error, while they arrive to Sentry without problems, they don't get posted to Slack.

I tried to make the cURL from the docker container to see if could be a certificates issue, but it's working correctly. Also, I have the default notification rules in Sentry, but I don't know if this can be related to the problem.

Any suggestions?.

Thanks!

**Comment by mattrobenolt** [comment]
Are you sure you have the Slack plugin installed in the worker container as well? It's needed in all of them.

**Comment by orlando** [comment]
Yes is installed in the workers too (using the same image). Actually I'm not getting any type of notifications (emails are not working either), I'll check this issue https://github.com/getsentry/sentry/issues/2528 to see if it helps.

Thanks @mattrobenolt

**Comment by orlando** [comment]
and yes, you were right, missing configuration in the workers. Thanks a bunch @mattrobenolt
