### ISSUE TITLE
Unable to filter messages by level

### ISSUE THREAD

**Issue by khuumi** [getsentry/sentry-slack#50]
Being able to to filter which messages to see in slack based on the level would be helpful. Right now the channel is being filled up with the lower levels while all I really would like to see are the errors.

**Comment by dcramer** [comment]
You can already do this via Project Settings > Rules (conditions).

Keep in mind, Sentry isn't logging, so "levels" becoming a bit meaningless when we're talking about errors.

**Comment by khuumi** [comment]
Thanks! Just found this in rules a minute ago.
