### ISSUE TITLE
Multiple notifications for every instance of an error

### ISSUE THREAD

**Issue by namit** [getsentry/sentry-slack#51]
In Sentry, multiple instances of an error get aggregated. And I get just one email for all those events. Everything is good so far. However, in Slack, we get notifications for each instance of the error. That just floods the slack channel. According to this https://github.com/getsentry/sentry/issues/1403 the issue is fixed in Sentry. As I get just one email and I can see the instances aggregated in Sentry, I'm guessing it's an issue with sentry-slack?

**Comment by mattrobenolt** [comment]
This is configurable in your Rules settings in Sentry itself. My guess is you have a rule that says to do this on every event, and not just new/regressions. sentry-slack has no control over choosing to send or not send data.

**Comment by namit** [comment]
The rules are just the default ones. Can you please help me identify which setting in "Rules" or "Notifications" would say that notifications should be sent for every event? Also, won't emails be using those notifications/rules settings as well? Emails don't get multiple notifications. Just Slack does.
