### ISSUE TITLE
Not visible under integrations with Sentry 8.6 and sentry-slack 0.5.0

### ISSUE THREAD

**Issue by robocop1988** [getsentry/sentry-slack#52]
Sentry slack plugin isn't visible under integrations on any projects using Sentry 8.6 with sentry-slack 0.5.0. It shows as installed under the Extensions and Modules heading on this page /manage/status/packages/. Tried restarting the sentry-web supervisor process to no avail. Not seeing anything related in the logs. Any suggestions on what to look at? Thanks!

**Comment by mattrobenolt** [comment]
Can you see it when you do `$ sentry plugins list` ?

**Comment by robocop1988** [comment]
The plugin shows up.

`sentry-slack 0.5.0`

**Comment by mattrobenolt** [comment]
I'm not sure then, it's definitely installed, and should be listed on the project's integration page, assuming _all_ processes have been restarted.

You could also try to install from `master` and see if that fixes it.

**Comment by robocop1988** [comment]
I'll give that a try. Thanks for responding!
