### ISSUE TITLE
Has no notifications

### ISSUE THREAD

**Issue by drakmail** [getsentry/sentry-slack#6]
Hello! I'm created sentry integration on slack.com (also I'm tryied to create just incoming webhook notification), then I'm installed sentry-slack and added slack URL. After trigerring error nothing happens =/ How I could turn on logging of a sentry-slack errors?

**Comment by coagulant** [comment]
I can confirm that sentry-slack==0.1.0 works fine with sentry==6.4.4

**Comment by bcsmith-fs** [comment]
Is there a fix for the issue, currently I have enabled sentry-slack 0.1.0 with sentry 7.4.3 and notifications do not come through.

**Comment by mattrobenolt** [comment]
I've pushed a new version (0.2.0) to pypi. We run this on getsentry.com without any issues, so this isn't valid.
