### ISSUE TITLE
I have confused need help

### ISSUE THREAD

**Issue by raajshekhar** [getsentry/sentry-slack#61]
I am new to the sentry, I have integrated the sentry with slack.

What I have done:
![sentryaddederror](https://user-images.githubusercontent.com/23142990/37877495-cdfa1566-3079-11e8-83cd-adf9e5dd3bbc.PNG)

Just added the webhook link of slack on sentry

If you don't mind, Please help me 

My mail Id: ursvraj@gmail.com

**Comment by dcramer** [comment]
https://sentry.io/support/
