### ISSUE TITLE
Feature request: let user choose tags to show in Slack notification

### ISSUE THREAD

**Issue by lorin** [getsentry/sentry-slack#7]
I'd love to be able to see if a particular Slack notification was related to production or staging. The Sentry plugin would need to be configurable to allow the user to select which tags to send to Sentry, so I could specify the "environment" tag.

Is this a feature you'd consider accepting? If so, I can take a shot at implementing it.

**Comment by CaliLuke** [comment]
I would also like this, but in our case we want to add the user's name so we can follow up proactively and make sure they don't have a bad time with the application. Might be a special case since we're aggressively "white glove" but I don't think it's an unreasonable thing to do. Just having a space to compose the json payload in the integration config would be enough.

**Comment by dcramer** [comment]
Pushed up some changes today which allow you to include both triggering rules as well as tags

**Comment by joshma** [comment]
Thanks @dcramer! Are these accessible from the "Rules" settings? Will they be live on app.getsentry.com soon?

**Comment by dcramer** [comment]
Sorry there's a mix of things going on here:

1. You can choose which tags to notify on via Rules (you can also do this with other event attributes)
2. The notifications can now include the tags so things are more obvious

**Comment by joshma** [comment]
Is the easiest way to force a tag to show to just require it does not equal `SOME_IMPOSSIBLE_VALUE`? Given https://github.com/getsentry/sentry-slack/commit/624ba94d22626028355edac701ecb6d3dcf5984c I'm assuming the changes to enable it just haven't been rolled out to sentry.com yet? (I'm in no hurry; just checking that I'm not missing anything.)

**Comment by dcramer** [comment]
@joshma if you just care about display, you tick the box and all tags will show up:

https://www.dropbox.com/s/sawj8wfhbbnm9o6/Screenshot%202015-07-24%2018.15.19.png?dl=0

(this is with, and without)

**Comment by dcramer** [comment]
Oh, and to be clear, they're in the middle of rolling out right now (should be live in 10m max)

**Comment by joshma** [comment]
:+1: sweet, many thanks

**Comment by adriantunez** [comment]
@dcramer , the dropbox link is giving to me 404 not found :( Anyway, with the new slack integration, I can see that in the rules I can choose which tags should be displayed, but what should I put if I want to show all of them in slack message? I couldn't find it in the documentation...

P.S: Sorry for commenting in a really old issue...

**Comment by dcramer** [comment]
@AdrianAntunez tags are unbounded so showing them all isn't something that we offer

**Comment by m1nty** [comment]
@dcramer, Would it be possible to include info from the "Additional Data" section from an Issue on the Slack message? That would be pretty cool as it can keep the Tags section clean as well.

P.S: Sorry for also commenting on a near 6 year old issue.
